version: "3.8"

services:
  flask-app:
    build: .
    container_name: beehive-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
      - MONGODB_CONNECTION_STRING=mongodb://mongo:27017/beehive
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
      - ADMIN_EMAILS=${ADMIN_EMAILS}
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: beehive-frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_CLERK_PUBLISHABLE_KEY=${VITE_CLERK_PUBLISHABLE_KEY}
    depends_on:
      - flask-app

  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=beehive
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
  